### ISSUE TITLE
Add ability to use cowsay's options

### ISSUE THREAD

**Issue by mikefrancis** [mikefrancis/moo#1]
At the moment we can use this by running the following Slash Command in Slack:

`/moo yoyoyo`

Which will give us a standard cow + text.

However, it would be great if we could make use of the [options in the cowsay package](https://www.npmjs.com/package/cowsay#usage-as-a-module), so that we could potentially do things like:

`/moo [options] yoyoyo`

To give us some different output.

## Steps to implement

* [ ] Install this for yourself by following the instructions on the README, so you're familiar with how it works
* [ ] Fork this repo
* [ ] Take a look at the docs in the [NPM Package](https://www.npmjs.com/package/cowsay#usage-as-a-module)
* [ ] Refactor `src/index.js` to include the ability to use the options
* [ ] Submit a PR

**Comment by azakordonets** [comment]
I would like to pick it up. Will update you with results in the nearest 2 days

**Comment by azakordonets** [comment]
Done, ready for review
