### ISSUE TITLE
Add `help` command

### ISSUE THREAD

**Issue by mikefrancis** [mikefrancis/moo#11]
At the moment the only way to view instructions on how to use moo are in the [README](https://github.com/mikefrancis/moo#usage) for this project.

As a user I want to be able to type `/moo help` and see a summary of the usage instructions, without the word `help` being passed to `cowsay.say()`.

## Checklist

* [ ] Check if text being sent `=== 'help'`
* [ ] If it is, show some help output
* [ ] Amend tests to suit

**Comment by azakordonets** [comment]
I would like to pick it up :) Will try to make it in the nearest 2-3 days

**Comment by azakordonets** [comment]
Done and ready for review

**Comment by azakordonets** [comment]
I guess you can close it now:) hey, if you gonna need help with other javascript projects - i would love to help - for me it's the best way to learn it
